---
title: "Recap"
author: "L. Wegner & J. Huang"
format: 
  html:
    self-contained: true
    theme: minty
editor: visual
---

## Recap

We are currently in week 7/14 - so halfway done!

Today's session serves the purpose to make sure that you have all the skills to master the second half of the course.

By now you should know how to do these elements:

| element: | content of exercise: |
|----------------------------------------------------|--------------------|
| log into the JupyterHub | ex. 2 |
| create a new Quarto Doc in a folder | ex. 2 |
| use the visual editing mode | ex. 2 |
| insert elements like bullet points and pictures | ex. 2 |
| insert executable cells and execute them | ex. 2 |
| save and render the Quarto document | ex. 2 |
| install a package and add it to the library | ex. 3 |
| read a package/function description | ex. 3 |
| load data from a package | ex. 3 |
| use a function from a package | ex. 3 |
| write a (simple) function | ex. 3/ex. 4 |
| use if-else-statements | ex. 3/ex. 4 |
| identify different data types | ex. 3/ex. 4 |
| create new variables | ex. 3/ex. 4 |
| create factor variables from character-values (like party-preference) | ex. 3/ex. 4 |
| do descriptive analysis with mean(), min(), range(), median() etc. | ex. 3/ex. 4 |
| insert comments | ex. 4 |
| create a simple line-/dot-plot with ggplot2 | ex. 5 |
| add colors to the plot | ex. 5 |
| add headlines and axis labels to the plot | ex. 5 |

Additional information on the elements that you should know by now can be found at OpenOlat under "helpful stuff" and in the course materials for the respective sessions listed above.

::: callout-caution
If you are not familiar with the elements listed above please repeat them! These are the basics that you will need to follow along through the remaining course.
:::
