---
title: "Exam recap"
format: 
  html:
    self-contained: true
    theme: minty
editor: visual
---

## For the exam:

-   There will be no coding "by hand" - but you should have basic code-understanding

-   structure follows the exam prep materials that are already online

-   Look into the tutorial slides and solutions for applications of concepts and methods

## Priorities (more + represent a greater importance)

1.  R_Markdown_Quarto (+)

2.  R_Basics_and_Algorithms_and_Structures (+)

3.  Data_and_Basic_Transformations_in_R (+)

4.  Transparency_and_Reproducability_in_Work_and_Research (+)

5.  Data_Visualisation (+)

6.  Foundations_of_SL (++)

7.  Linear_Regression_Part_1 (+++)

8.  Linear_Regression_Part_2 (+++)

9.  LPM_Logit (++)

10. evaluation_cv_dimensionality (++)

11. Trees (+)

## Points: 

-   when 1 answer is right and you get it right -\> 2p

-   when 2 answers are right and you get both right -\> 2p

-   when 2 answers are right and you get one right and one wrong // when 1 is right and you choose it and another one -\> 0p

-   when 2 answers re right and you get only one right and leave the other answer unmarked -\> 1p

-   for all other questions: you get points for right answers, we do not take points from you for wrong answers
